Imported Upstream version 3.3.5

diff --git a/tests/cert-tests/aki b/tests/cert-tests/aki
--- a/tests/cert-tests/aki
+++ b/tests/cert-tests/aki
@@ -24,18 +24,29 @@ set -e
 
 srcdir=${srcdir:-.}
 CERTTOOL=${CERTTOOL:-../../src/certtool$EXEEXT}
+DIFF=${DIFF:-diff}
+if ! test -z "${VALGRIND}";then
+VALGRIND="${LIBTOOL:-libtool} --mode=execute ${VALGRIND}"
+fi
 
-$CERTTOOL --certificate-info --infile $srcdir/aki-cert.pem \
-	  --outfile tmp-aki.pem
-
-diff $srcdir/aki-cert.pem tmp-aki.pem
+$VALGRIND $CERTTOOL --certificate-info --infile $srcdir/aki-cert.pem \
+	  |grep -v "Algorithm Security Level" > tmp-aki.pem
 rc=$?
 
-rm -f tmp-aki.pem
+if test "$rc" != "0"; then
+  echo "info failed"
+  exit $rc
+fi
+
+
+$DIFF $srcdir/aki-cert.pem tmp-aki.pem
+rc=$?
 
 # We're done.
 if test "$rc" != "0"; then
   exit $rc
 fi
+
+rm -f tmp-aki.pem
 
 exit 0
diff --git a/tests/cert-tests/pathlen b/tests/cert-tests/pathlen
--- a/tests/cert-tests/pathlen
+++ b/tests/cert-tests/pathlen
@@ -24,21 +24,40 @@ set -e
 
 srcdir=${srcdir:-.}
 CERTTOOL=${CERTTOOL:-../../src/certtool$EXEEXT}
+DIFF=${DIFF:-diff}
+if ! test -z "${VALGRIND}";then
+VALGRIND="${LIBTOOL:-libtool} --mode=execute ${VALGRIND}"
+fi
 
-$CERTTOOL --certificate-info --infile $srcdir/ca-no-pathlen.pem \
-	  --outfile new-ca-no-pathlen.pem
-$CERTTOOL --certificate-info --infile $srcdir/no-ca-or-pathlen.pem \
-	  --outfile new-no-ca-or-pathlen.pem
+$VALGRIND $CERTTOOL --certificate-info --infile $srcdir/ca-no-pathlen.pem \
+	  |grep -v "Algorithm Security Level" > new-ca-no-pathlen.pem
+rc=$?
 
-diff $srcdir/ca-no-pathlen.pem new-ca-no-pathlen.pem
+if test "$rc" != "0"; then
+  echo "info 1 failed"
+  exit $rc
+fi
+
+$VALGRIND $CERTTOOL --certificate-info --infile $srcdir/no-ca-or-pathlen.pem \
+	  |grep -v "Algorithm Security Level" > new-no-ca-or-pathlen.pem
+rc=$?
+
+if test "$rc" != "0"; then
+  echo "info 2 failed"
+  exit $rc
+fi
+
+$DIFF $srcdir/ca-no-pathlen.pem new-ca-no-pathlen.pem
 rc1=$?
-diff $srcdir/no-ca-or-pathlen.pem new-no-ca-or-pathlen.pem
+$DIFF $srcdir/no-ca-or-pathlen.pem new-no-ca-or-pathlen.pem
 rc2=$?
 
-rm -f new-ca-no-pathlen.pem new-no-ca-or-pathlen.pem
 
 # We're done.
 if test "$rc1" != "0"; then
   exit $rc1
 fi
+
+rm -f new-ca-no-pathlen.pem new-no-ca-or-pathlen.pem
+
 exit $rc2
diff --git a/tests/cert-tests/template-test b/tests/cert-tests/template-test
--- a/tests/cert-tests/template-test
+++ b/tests/cert-tests/template-test
@@ -18,7 +18,7 @@
 # along with GnuTLS; if not, write to the Free Software Foundation,
 # Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 
-set -e
+#set -e
 
 srcdir=${srcdir:-.}
 CERTTOOL=${CERTTOOL:-../../src/certtool$EXEEXT}
@@ -30,20 +30,194 @@ if test "$TSTAMP" != "1158962400"; then
     exit 77
 fi
 
+# Note that in rare cases this test may fail because the
+# time set using datefudge could have changed since the generation
+# (if example the system was busy)
+
+rc=1
+counter=1
+
+while [ "$rc" != "0" -a $counter -le 3 ]
+do
+      
 datefudge "2007-04-22" \
     $CERTTOOL --generate-self-signed \
     --load-privkey $srcdir/template-test.key \
     --template $srcdir/template-test.tmpl \
     --outfile tmp-tt.pem 2>/dev/null
 
-diff $srcdir/template-test.pem tmp-tt.pem
+diff $srcdir/template-test.pem tmp-tt.pem >/dev/null 2>&1
 rc=$?
-
-rm -f tmp-tt.pem
+counter=`expr $counter + 1` 
+done
 
 # We're done.
 if test "$rc" != "0"; then
+  echo "Test 1 failed"
   exit $rc
 fi
+
+rm -f tmp-tt.pem
+
+rc=1
+counter=1
+
+while [ "$rc" != "0" -a $counter -le 3 ]
+do
+datefudge "2007-04-22" \
+    $CERTTOOL --generate-self-signed \
+    --load-privkey $srcdir/template-test.key \
+    --template $srcdir/template-utf8.tmpl \
+    --outfile tmp-tt.pem 2>/dev/null
+
+diff $srcdir/template-utf8.pem tmp-tt.pem >/dev/null 2>&1
+rc=$?
+counter=`expr $counter + 1` 
+done
+
+# We're done.
+if test "$rc" != "0"; then
+  echo "Test 2 (UTF8) failed"
+  exit $rc
+fi
+
+rm -f tmp-tt.pem
+
+rc=1
+counter=1
+
+while [ "$rc" != "0" -a $counter -le 3 ]
+do
+datefudge "2007-04-22" \
+    $CERTTOOL --generate-self-signed \
+    --load-privkey $srcdir/template-test.key \
+    --template $srcdir/template-dn.tmpl \
+    --outfile tmp-tt.pem 2>/dev/null
+
+diff $srcdir/template-dn.pem tmp-tt.pem >/dev/null 2>&1
+rc=$?
+counter=`expr $counter + 1` 
+done
+
+# We're done.
+if test "$rc" != "0"; then
+  echo "Test 3 (DN) failed"
+  exit $rc
+fi
+
+rm -f tmp-tt.pem
+
+datefudge "2007-04-22" \
+    $CERTTOOL --generate-self-signed \
+    --load-privkey $srcdir/template-test.key \
+    --template $srcdir/template-dn-err.tmpl \
+    --outfile tmp-tt.pem 2>/dev/null
+rc=$?
+
+if test "$rc" = "0"; then
+  echo "Test 3 (DN-err) failed"
+  exit $rc
+fi
+
+rm -f tmp-tt.pem
+
+rc=1
+counter=1
+
+while [ "$rc" != "0" -a $counter -le 3 ]
+do
+datefudge "2007-04-22" \
+    $CERTTOOL --generate-self-signed \
+    --load-privkey $srcdir/template-test.key \
+    --template $srcdir/template-overflow.tmpl \
+    --outfile tmp-tt.pem 2>/dev/null
+
+diff $srcdir/template-overflow.pem tmp-tt.pem >/dev/null 2>&1 
+rc=$?
+counter=`expr $counter + 1` 
+done
+
+# We're done.
+if test "$rc" != "0"; then
+  echo "Test 4 (overflow1) failed"
+  exit $rc
+fi
+
+rm -f tmp-tt.pem
+
+rc=1
+counter=1
+
+while [ "$rc" != "0" -a $counter -le 3 ]
+do
+datefudge "2007-04-22" \
+    $CERTTOOL --generate-self-signed \
+    --load-privkey $srcdir/template-test.key \
+    --template $srcdir/template-overflow2.tmpl \
+    --outfile tmp-tt.pem 2>/dev/null
+
+diff $srcdir/template-overflow2.pem tmp-tt.pem >/dev/null 2>&1
+rc=$?
+counter=`expr $counter + 1` 
+done
+
+# We're done.
+if test "$rc" != "0"; then
+  echo "Test 5 (overflow2) failed"
+  exit $rc
+fi
+
+rm -f tmp-tt.pem
+
+rc=1
+counter=1
+
+while [ "$rc" != "0" -a $counter -le 3 ]
+do
+datefudge "2007-04-22" \
+    $CERTTOOL --generate-self-signed \
+    --load-privkey $srcdir/template-test.key \
+    --template $srcdir/template-date.tmpl \
+    --outfile tmp-tt.pem 2>/dev/null
+
+diff $srcdir/template-date.pem tmp-tt.pem >/dev/null 2>&1
+rc=$?
+counter=`expr $counter + 1` 
+done
+
+# We're done.
+if test "$rc" != "0"; then
+  echo "Test 6 (explicit dates) failed"
+  exit $rc
+fi
+
+rm -f tmp-tt.pem
+
+# Test name constraints generation
+
+rc=1
+counter=1
+
+while [ "$rc" != "0" -a $counter -le 3 ]
+do
+datefudge "2007-04-22" \
+    $CERTTOOL --generate-self-signed \
+    --load-privkey $srcdir/template-test.key \
+    --template $srcdir/template-nc.tmpl \
+    --outfile tmp-tt.pem 2>/dev/null
+
+diff $srcdir/template-nc.pem tmp-tt.pem >/dev/null 2>&1
+rc=$?
+counter=`expr $counter + 1` 
+done
+
+# We're done.
+if test "$rc" != "0"; then
+  echo "Test 7 (name constraints) failed"
+  exit $rc
+fi
+
+rm -f tmp-tt.pem
+
 
 exit 0
